#ifndef ERRORS_H
#define ERRORS_H

enum {  NO_ERROR,
		ERR_UNK_OPTION,
		ERR_NOT_FOUND,
		ERR_MALLOC_HDR,
		ERR_NOT_BMP,
		ERR_MALLOC_NFO,
		ERR_NO_NFOHDR,
		ERR_NOT_ROUNDED,
		ERR_TOO_BIG,
		ERR_COMPRESSED,
		ERR_MALLOC_BMPD,
		ERR_NOT_SUPRTD,
		ERR_MAX_COLS1,
		ERR_BITFIELDS,
		ERR_TRNSP,
		ERR_PADDING,
		ERR_MALLOC_TMPD,
		ERR_MALLOC_TMPC,
		ERR_MAX_COLS2,
		ERR_MALLOC_TMPI,
		ERR_PASS,
		ERR_PASS1,
		ERR_PASS2,
		ERR_PASS3,
		ERR_PASS4,
		ERR_TMPI_FAILED,
		ERR_WRONG_PAL,
		ERR_MAX_TILES,
		ERR_MALLOC_CGBT
};

/*

#define ERR_NOT_8BPP	44
#define ERR_BI_RLE		5
#define ERR_TOO_BIG		7
#define ERR_MALLOC_BMIC	8
#define ERR_MALLOC_TMPC 10
#define ERR_MALLOC_TMPI	11
#define	ERR_MALLOC_BMIT	12
#define	ERR_MAX_TILES	13
#define ERR_MALLOC_CGBT	14
#define ERR_PASS1		15
#define ERR_PASS2		16
#define ERR_PASS3		17
#define ERR_PASS4		18
#define ERR_TMPI_FAILED	19
#define ERR_UNK_OPTION	20
#define ERR_WRONG_PAL	21
#define ERR_PADDING		22
*/
#endif
